config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"

  get "movies/filter/:filter" => "movies#index" , as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  get "signup" => "users#new"
  get "signin" => "sessions#new"
end

app/models/genre.rb
class Genre < ApplicationRecord
  before_save :set_slug
  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations
  validates :name, presence: true, uniqueness: true

  def to_param
    slug
  end

  private
  def set_slug
    self.slug = name.parameterize
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre
  before_action :get_genres
  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to new_genre_path
    else
      render :new
    end
  end

  def destroy
    @genre.destroy
    redirect_to new_genre_path
  end

  def update
    if @genre.update(genre_params)
      redirect_to new_genre_path
    else
      render :new
    end
  end

  def edit
  end

  private
  def genre_params
    params.require(:genre)
          .permit(:name)
  end

  def set_genre
    @genre = Genre.find_by!(slug: params[:id]) if params[:id]
  end
  def get_genres
    @genres = Genre.all
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: @genre) do |f| %>

	<%= render 'shared/errors', object: @genre %>

	<% if @genres.present? %>
		<div class="genre">
			<h4>Genres</h4>
			<ul>
				<% @genres.each do |g|%>
					<li>
						<%= g.name %>
						<% if current_user_admin? %>
							<%= link_to "delete", genre_path(g), class: "delete",
													data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
							<%= link_to "edit", edit_genre_path(g) %>
						<% end %>
					</li>
				<% end %>
			</ul>
		</div>
	<% end %>



	<% if @genre.name.present? %>
		<%= f.label "Genre #{:name}" %>
		<%= f.text_field :name, autofocus: true %>
	<% else %>
		<%= f.label "New Genre #{:name}" %>
		<%= f.text_field :name, autofocus: true, placeholder: 'Enter New Genre'  %>
	<% end %>

	<%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= render 'form', model: @genre  %>

app/views/genres/new.html.erb
<h1>Create a New Genre</h1>
<%= render 'form', model: @genre  %>